# Generated by Django 5.0.6 on 2024-06-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locomotives',
            fields=[
                ('motive_power', models.CharField(max_length=50)),
                ('gauge', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('traction', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=25)),
                ('numbers', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('axles', models.CharField(max_length=50)),
                ('numbers_built', models.IntegerField()),
                ('production', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
