# Generated by Django 5.0.6 on 2024-06-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locomotives',
            new_name='Locomotive',
        ),
    ]
